#!/usr/bin/env python3
"""Generate original PCM cues offline, keeping floating-point math out of playback."""
import argparse,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
lengths=[0,45,60,120,110,240,30,35,70,90,130]
rows=['/* Generated by tools/generate_tally_audio.py. Original synthesized cues. */','#pragma once','#include <stdint.h>']
for s,ms in enumerate(lengths):
    if not ms:continue
    n=ms*16;data=[]
    for i in range(n):
        t=i/16000;x=i/n;f=700;slope=0
        if s==1:f=1050;slope=8000
        elif s==2:f=460;slope=-2300
        elif s==3:f=660 if x<.5 else 440
        elif s==4:f=440 if x<.5 else 880
        elif s==5:f=660 if x<1/3 else 990 if x<2/3 else 1320
        elif s==6:f=520
        elif s==7:f=940
        elif s==8:f=880;slope=1800
        elif s==9:f=240
        elif s==10:f=180
        parts=3 if s==5 else 2 if s in (3,4) else 1
        segment=n//parts;local=i%segment
        envelope=min(1,local/48)*min(1,(segment-1-local)/160)*(1-.4*x)
        phase=2*math.pi*(f*t+.5*slope*t*t)
        data.append(int((math.sin(phase)+.18*math.sin(2*phase))*5600*envelope))
    rows.append(f'static const int16_t tc_pcm_{s}[{n}] = {{')
    for j in range(0,n,16):rows.append('    '+','.join(map(str,data[j:j+16]))+',')
    rows.append('};')
rows+=['static const unsigned tc_pcm_lengths[] = {'+','.join(str(x*16) for x in lengths)+'};','static const int16_t *const tc_pcm_data[] = {0,'+','.join(f'tc_pcm_{i}' for i in range(1,11))+'};']
text='\n'.join(rows)+'\n';target=ROOT/'main/tally/tally_pcm_data.h'
if a.check:assert target.read_text()==text,'Regenerate PCM assets';print('Tally PCM assets: reproducible, no playback-time floating point PASS')
else:target.write_text(text)
